-- MySQL Script generated by MySQL Workbench
-- 07/06/16 20:59:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yii-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `yii-ecommerce` ;

-- -----------------------------------------------------
-- Schema yii-ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yii-ecommerce` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `yii-ecommerce` ;

-- -----------------------------------------------------
-- Table `yii-ecommerce`.`tb_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii-ecommerce`.`tb_category` ;

CREATE TABLE IF NOT EXISTS `yii-ecommerce`.`tb_category` (
  `cd_category` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nm_category` VARCHAR(80) NOT NULL COMMENT '',
  PRIMARY KEY (`cd_category`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii-ecommerce`.`tb_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii-ecommerce`.`tb_product` ;

CREATE TABLE IF NOT EXISTS `yii-ecommerce`.`tb_product` (
  `cd_product` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nm_product` VARCHAR(80) NOT NULL COMMENT '',
  `ds_product` LONGTEXT NOT NULL COMMENT '',
  `ds_imagem` LONGTEXT NULL COMMENT '',
  `vl_product` DOUBLE(10,2) NOT NULL COMMENT '',
  `ds_specs` LONGTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`cd_product`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii-ecommerce`.`tb_product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii-ecommerce`.`tb_product_category` ;

CREATE TABLE IF NOT EXISTS `yii-ecommerce`.`tb_product_category` (
  `cd_product_category` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cd_product` INT NOT NULL COMMENT '',
  `cd_category` INT NOT NULL COMMENT '',
  INDEX `fk_tb_product_has_tb_category_tb_category1_idx` (`cd_category` ASC)  COMMENT '',
  INDEX `fk_tb_product_has_tb_category_tb_product_idx` (`cd_product` ASC)  COMMENT '',
  PRIMARY KEY (`cd_product_category`)  COMMENT '',
  CONSTRAINT `fk_tb_product_has_tb_category_tb_product`
    FOREIGN KEY (`cd_product`)
    REFERENCES `yii-ecommerce`.`tb_product` (`cd_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_product_has_tb_category_tb_category1`
    FOREIGN KEY (`cd_category`)
    REFERENCES `yii-ecommerce`.`tb_category` (`cd_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii-ecommerce`.`tb_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii-ecommerce`.`tb_user` ;

CREATE TABLE IF NOT EXISTS `yii-ecommerce`.`tb_user` (
  `cd_user` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nm_user` VARCHAR(60) NULL COMMENT '',
  `nm_login` VARCHAR(60) NULL COMMENT '',
  `ds_password` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`cd_user`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii-ecommerce`.`tb_user_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii-ecommerce`.`tb_user_address` ;

CREATE TABLE IF NOT EXISTS `yii-ecommerce`.`tb_user_address` (
  `cd_user_address` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cd_user` INT NOT NULL COMMENT '',
  `ds_cep` VARCHAR(12) NULL COMMENT '',
  `nm_address` VARCHAR(60) NULL COMMENT '',
  `nm_neighborhood` VARCHAR(45) NULL COMMENT '',
  `nm_city` VARCHAR(45) NULL COMMENT '',
  `nm_province` VARCHAR(45) NULL COMMENT '',
  `nm_country` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`cd_user_address`)  COMMENT '',
  INDEX `fk_tb_user_address_tb_user1_idx` (`cd_user` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_user_address_tb_user1`
    FOREIGN KEY (`cd_user`)
    REFERENCES `yii-ecommerce`.`tb_user` (`cd_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yii-ecommerce`.`tb_shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii-ecommerce`.`tb_shopping_cart` ;

CREATE TABLE IF NOT EXISTS `yii-ecommerce`.`tb_shopping_cart` (
  `cd_shopping_cart` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cd_user` INT NOT NULL COMMENT '',
  `cd_user_address` INT NULL COMMENT '',
  `cd_product` INT NOT NULL COMMENT '',
  `qt_items` INT NULL COMMENT '',
  `vl_total` DOUBLE(10,2) NULL COMMENT '',
  INDEX `fk_tb_user_has_tb_product_tb_product1_idx` (`cd_product` ASC)  COMMENT '',
  INDEX `fk_tb_user_has_tb_product_tb_user1_idx` (`cd_user` ASC)  COMMENT '',
  PRIMARY KEY (`cd_shopping_cart`)  COMMENT '',
  INDEX `fk_tb_shopping_cart_tb_user_address1_idx` (`cd_user_address` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_user_has_tb_product_tb_user1`
    FOREIGN KEY (`cd_user`)
    REFERENCES `yii-ecommerce`.`tb_user` (`cd_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_user_has_tb_product_tb_product1`
    FOREIGN KEY (`cd_product`)
    REFERENCES `yii-ecommerce`.`tb_product` (`cd_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_shopping_cart_tb_user_address1`
    FOREIGN KEY (`cd_user_address`)
    REFERENCES `yii-ecommerce`.`tb_user_address` (`cd_user_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `yii-ecommerce`.`tb_category`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii-ecommerce`;
INSERT INTO `yii-ecommerce`.`tb_category` (`cd_category`, `nm_category`) VALUES (DEFAULT, 'Jogos');
INSERT INTO `yii-ecommerce`.`tb_category` (`cd_category`, `nm_category`) VALUES (DEFAULT, 'Jogos eletrônicos');

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii-ecommerce`.`tb_product`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii-ecommerce`;
INSERT INTO `yii-ecommerce`.`tb_product` (`cd_product`, `nm_product`, `ds_product`, `ds_imagem`, `vl_product`, `ds_specs`) VALUES (DEFAULT, 'Fallout IV', 'ACTION RPG OPEN WORLD', NULL, 99.00, '- PRODUTO NOVO');
INSERT INTO `yii-ecommerce`.`tb_product` (`cd_product`, `nm_product`, `ds_product`, `ds_imagem`, `vl_product`, `ds_specs`) VALUES (DEFAULT, 'For the Honor', 'ACTION RPG LINEAR', NULL, 120.00, '- PRE ORDER');

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii-ecommerce`.`tb_product_category`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii-ecommerce`;
INSERT INTO `yii-ecommerce`.`tb_product_category` (`cd_product_category`, `cd_product`, `cd_category`) VALUES (DEFAULT, 1, 1);
INSERT INTO `yii-ecommerce`.`tb_product_category` (`cd_product_category`, `cd_product`, `cd_category`) VALUES (DEFAULT, 1, 2);
INSERT INTO `yii-ecommerce`.`tb_product_category` (`cd_product_category`, `cd_product`, `cd_category`) VALUES (DEFAULT, 2, 1);
INSERT INTO `yii-ecommerce`.`tb_product_category` (`cd_product_category`, `cd_product`, `cd_category`) VALUES (DEFAULT, 2, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii-ecommerce`.`tb_user`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii-ecommerce`;
INSERT INTO `yii-ecommerce`.`tb_user` (`cd_user`, `nm_user`, `nm_login`, `ds_password`) VALUES (DEFAULT, 'Francisco João', 'francisco', 'francisco');

COMMIT;


-- -----------------------------------------------------
-- Data for table `yii-ecommerce`.`tb_user_address`
-- -----------------------------------------------------
START TRANSACTION;
USE `yii-ecommerce`;
INSERT INTO `yii-ecommerce`.`tb_user_address` (`cd_user_address`, `cd_user`, `ds_cep`, `nm_address`, `nm_neighborhood`, `nm_city`, `nm_province`, `nm_country`) VALUES (DEFAULT, 1, '11515 - 100', 'Rua Lilás, 45', 'Jardim das Rosas', 'São Paulo', 'São Paulo - SP', 'Brasil');

COMMIT;

